-- DTS同步标准表
-- DROP TABLE HIVE_FACE_DETECT_RL;
-- DROP TABLE CAR_DETECT_INFO;
-- DROP TABLE EFENCE_DETECT_INFO;
-- DROP TABLE TB_DEVICE_ROUND;
-- DROP TABLE VEHICLE_FRONT_FACE_INFO;
CREATE EXTERNAL TABLE IF NOT EXISTS HIVE_FACE_DETECT_RL(
 FACE_ID STRING,
 PERSON_ID STRING,
 INFO_ID STRING,
 DEVICE_ID STRING,
 IN_OUT_TYPE INT,
 CREATE_TIME STRING,
 SHOT_TIME STRING,
 DATA_SRC INT)
PARTITIONED BY (
 STAT_DAY STRING,
 `HOUR` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS CAR_DETECT_INFO(
 INFO_ID STRING,
 DEVICE_ID STRING,
 JGSK STRING,
 HPHM STRING,
 HPYS INT,
 JGRQ STRING,
 TOLLGATE_ID STRING,
 DATA_SRC STRING)
PARTITIONED BY (
 STAT_DAY STRING,
 `HOUR` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS EFENCE_DETECT_INFO(
 DEVICE_ID STRING,
 MSISDN STRING,
 IMEI STRING,
 IMSI STRING,
 LONGITUDE STRING,
 LATITUDE STRING,
 JGSK STRING,
 JGRQ STRING,
 JGRQSJ STRING,
 MAC STRING,
 DATA_SRC int)
PARTITIONED BY (
 STAT_DAY STRING,
 `HOUR` STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE  IF NOT EXISTS TB_DEVICE_ROUND(
  DEVICE_ID1 STRING,
  DEVICE_TYPE1 STRING,
  DEVICE_ID2 STRING,
  DEVICE_TYPE2 STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

-- 分布相关表
-- DROP TABLE DM_RELATION_DISTRIBUTE_DETAIL;
-- DROP TABLE DM_RELATION_DISTRIBUTE_STAT;
-- DROP TABLE DM_ID_DISTRIBUTE_DAY;

CREATE EXTERNAL TABLE IF NOT EXISTS DM_RELATION_DISTRIBUTE_DETAIL(
  DEVICE_ID STRING,
  OBJECT_ID_A STRING,
 TYPE_A STRING,
 OBJECT_ID_B STRING,
 TYPE_B STRING,
 TIMESTAMP_A BIGINT,
 TIMESTAMP_B BIGINT,
 SUB_TIME BIGINT,
 ADD_TIME STRING)
PARTITIONED BY (
 STAT_DATE STRING,
 `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_RELATION_DISTRIBUTE_STAT(
 DEVICE_ID STRING,
 OBJECT_ID_A STRING,
 TYPE_A STRING,
 OBJECT_ID_B STRING,
 TYPE_B STRING,
 TOTAL BIGINT,
 TOTAL_A BIGINT,
 TOTAL_B BIGINT,
 ADD_TIME STRING)
PARTITIONED BY (
 STAT_DATE STRING,
 `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_ID_DISTRIBUTE_DAY(
 OBJECT_ID STRING,
 TOTAL BIGINT)
PARTITIONED BY (
 STAT_DATE STRING,
 `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

-- LCSS相关表
-- DROP TABLE DM_LCSS;
-- DROP TABLE DM_LCSS_DAY;
-- DROP TABLE DM_LCSS_OBJECT_DAY;
-- DROP TABLE DM_LCSS_OBJECT_HOUR;
CREATE EXTERNAL TABLE IF NOT EXISTS DM_LCSS_OBJECT_HOUR(
 OBJECT_ID STRING,
 SEQ_LENGTH INT,
 SEQ_STR STRING
)PARTITIONED BY(STAT_DATE STRING, TYPE STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_LCSS_OBJECT_DAY(
 OBJECT_ID STRING,
 SEQ_LENGTH INT,
 SEQ_STR STRING
)PARTITIONED BY(STAT_DATE STRING, TYPE STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_LCSS_DAY(
 OBJECT_ID_A STRING,
 TYPE_A INT,
 OBJECT_ID_B STRING,
 TYPE_B INT,
 SIM_SCORE_AB DOUBLE,
 SIM_SCORE_BA DOUBLE,
 SIM_SCORE DOUBLE,
 TIME_SUM INT,
 SEQ_SAME_LENGTH INT,
 SIM_SEQ_STR STRING,
 SEQ_LENGTH_A INT,
 SEQ_STR_A STRING,
 SEQ_LENGTH_B INT,
 SEQ_STR_B STRING,
 FIRST_TIME STRING,
 FIRST_DEVICE STRING,
 LAST_TIME STRING,
 LAST_DEVICE STRING
)PARTITIONED BY(STAT_DATE STRING, `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_LCSS(
 OBJECT_ID_A STRING,
 TYPE_A INT,
 OBJECT_ID_B STRING,
 TYPE_B INT,
 SIM_SCORE_AB DOUBLE,
 SIM_SCORE_BA DOUBLE,
 SIM_SCORE DOUBLE,
 TIME_SUM INT,
 SEQ_SAME_LENGTH INT,
 SEQ_LENGTH_A INT,
 SEQ_LENGTH_B INT,
 FIRST_TIME STRING,
 FIRST_DEVICE STRING,
 LAST_TIME STRING,
 LAST_DEVICE STRING
)PARTITIONED BY(STAT_DATE STRING, REL_TYPE STRING, `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");


-- 熵值法相关表结构
-- DROP TABLE DM_ENTROPY_RESULT;
-- DROP TABLE DM_ENTROPY_WEIGHT;
CREATE EXTERNAL TABLE IF NOT EXISTS DM_ENTROPY_WEIGHT(
 INDEX_NAME STRING,
 WEIGHT DOUBLE
)PARTITIONED BY(STAT_DATE STRING, `TYPE` STRING, PARENT_INDEX_NAME STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_ENTROPY_RESULT(
 OBJECT_ID_A STRING,
 TYPE_A INT,
 OBJECT_ID_B STRING,
 TYPE_B INT,
 SCORE DOUBLE,
 TIMES INT,
 FIRST_TIME STRING,
 FIRST_DEVICE STRING,
 LAST_TIME STRING,
 LAST_DEVICE STRING
)PARTITIONED BY(STAT_DATE STRING, REL_TYPE STRING, `TYPE` STRING, RESULT_TYPE STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

-- DTW相关表结构
-- DROP TABLE DM_DTW_ITEMS;
-- DROP TABLE DM_DTW;

CREATE EXTERNAL TABLE IF NOT EXISTS DM_DTW_ITEMS (
 OBJECT_ID_A  STRING,
 TYPE_A  STRING,
 OBJECT_ID_B  STRING,
 TYPE_B  STRING,
 TIMES  BIGINT,
 SCORE  DOUBLE,
 FIRST_TIME  BIGINT,
 FIRST_DEVICE  STRING,
 LAST_TIME  BIGINT,
 LAST_DEVICE  STRING,
 GAP_A  BIGINT,
 MATCH_A_PER  DOUBLE,
 GAP_B  BIGINT,
 MATCH_B_PER  DOUBLE,
 COST_A  DOUBLE,
 COST_A_NORMAL  DOUBLE,
 COST_B  DOUBLE,
 COST_B_NORMAL  DOUBLE)
PARTITIONED BY (
 STAT_DATE  STRING,
 `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE  IF NOT EXISTS `DM_DTW`(
 `OBJECT_ID_A` STRING,
 `TYPE_A` STRING,
 `OBJECT_ID_B` STRING,
 `TYPE_B` STRING,
 `TIMES` BIGINT,
 `SCORE` DOUBLE,
 `FIRST_TIME` BIGINT,
 `FIRST_DEVICE` STRING,
 `LAST_TIME` BIGINT,
 `LAST_DEVICE` STRING,
 `DAYS` BIGINT)
  PARTITIONED BY (
 `STAT_DATE` STRING,
 `TYPE` STRING,
 `REL_TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

-- FPTREE相关表结构
-- DROP TABLE DM_FPTREE_FREREQUENT_ITEMS;
-- DROP TABLE DM_FPTREE;

CREATE EXTERNAL TABLE IF NOT EXISTS DM_FPTREE_FREREQUENT_ITEMS(
 OBJECT_ID_A STRING,
 TYPE_A STRING,
 OBJECT_ID_B STRING,
 TYPE_B STRING,
 TIMES BIGINT,
 SCORE DOUBLE,
 FIRST_TIME BIGINT,
 FIRST_DEVICE STRING,
 LAST_TIME BIGINT,
 LAST_DEVICE STRING,
 SET_NUM BIGINT)
 PARTITIONED BY (
 STAT_DATE STRING,
 `TYPE` STRING,
 CAL_TYPE STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");


CREATE EXTERNAL TABLE IF NOT EXISTS DM_FPTREE(
 OBJECT_ID_A STRING,
 TYPE_A STRING,
 OBJECT_ID_B STRING,
 TYPE_B STRING,
 TIMES BIGINT,
 SCORE DOUBLE,
 FIRST_TIME BIGINT,
 FIRST_DEVICE STRING,
 LAST_TIME BIGINT,
 LAST_DEVICE STRING)
 PARTITIONED BY (
 STAT_DATE STRING,
 `TYPE` STRING,
 REL_TYPE STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

-- 按场所伴随分析表结构
-- DROP TABLE SV_ACCOMPANY;
-- DROP TABLE SV_ACCOMPANY_DAY;

CREATE EXTERNAL TABLE IF NOT EXISTS SV_ACCOMPANY_DAY(
 DEVICE_ID STRING,
 OBJECT_ID_A STRING,
 TYPE_A STRING,
 OBJECT_ID_B STRING,
 TYPE_B STRING,
 TODAY_TIMES BIGINT,
 TIMESTAMP_A STRING,
 TIMESTAMP_B STRING,
 ADD_TIME STRING)
 PARTITIONED BY(
  TYPE STRING,
  STAT_DATE STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS SV_ACCOMPANY(
 OBJECT_ID_A STRING,
 TYPE_A STRING,
 OBJECT_ID_B STRING,
 TYPE_B STRING,
 TIMES BIGINT,
 SCORE DOUBLE,
 FIRST_TIME BIGINT,
 FIRST_DEVICE STRING,
 LAST_TIME BIGINT,
 LAST_DEVICE STRING,
 ADD_TIME STRING)
 PARTITIONED BY(
  TYPE STRING,
  STAT_DATE STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");


 CREATE EXTERNAL TABLE IF NOT EXISTS  DM_RELATION(
  OBJECT_ID_A STRING,
  TYPE_A STRING,
  OBJECT_ATTR_A STRING,
  OBJECT_ID_B STRING,
  TYPE_B STRING,
  OBJECT_ATTR_B STRING,
  SCORE INT,
  FIRST_TIME BIGINT,
  FIRST_DEVICE STRING,
  LAST_TIME BIGINT,
  LAST_DEVICE STRING,
  TOTAL INT,
  REL_ATTR STRING)
 PARTITIONED BY (
  STAT_DATE STRING,
  REL_TYPE STRING,
  REL_ID STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

 CREATE EXTERNAL TABLE IF NOT EXISTS  TB_ACCOMPANY_EVALUATION_RESULT(
 POSID STRING,
 NEGID STRING,
 THR_OR_FPR DOUBLE,
 VAL_OR_TPR DOUBLE,
 EVALUATION STRING)
 PARTITIONED BY (
 ALG STRING,
 BD STRING,
 AD STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

 CREATE EXTERNAL TABLE  IF NOT EXISTS TB_ACC_SAMPLE(
   ID STRING,
   OBJA STRING,
   OBJB STRING,
   LABEL STRING)
   PARTITIONED BY (
   TYPE STRING COMMENT 'CAR-CAR/IMSI-IMSI/MAC-MAC/PERSON-PERSON/CAR-IMSI/CAR-MAC',
    BD STRING  )
 ROW FORMAT DELIMITED
 FIELDS TERMINATED BY ','
 STORED AS TEXTFILE;


CREATE EXTERNAL TABLE IF NOT EXISTS FACE_INFO(
 INFO_ID STRING,
 JGRQ STRING,
 JGSK STRING,
 DEVICE_ID STRING,
 VIID_OBJECT_ID STRING,
 RELATED_LIST STRING,
 DATA_SRC STRING)
PARTITIONED BY (
 STAT_DAY STRING,
 `HOUR` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS VIDEO_PERSON_INFO(
 INFO_ID STRING,
 JGRQ STRING,
 JGSK STRING,
 DEVICE_ID STRING,
 VIID_OBJECT_ID STRING,
 RELATED_LIST STRING,
 DATA_SRC STRING)
PARTITIONED BY (
 STAT_DAY STRING,
 `HOUR` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_COMMON_STAT_DAY(
 OBJECT_ID_A STRING,
 TYPE_A INT,
 OBJECT_ID_B STRING,
 TYPE_B INT,
 CNT INT,
 REMARK STRING,
 FIRST_TIME STRING,
 LAST_TIME STRING
)PARTITIONED BY(STAT_DATE STRING, `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS DM_COMMON_STAT(
 OBJECT_ID_A STRING,
 TYPE_A INT,
 OBJECT_ID_B STRING,
 TYPE_B INT,
 CNT INT,
 REMARK STRING,
 FIRST_TIME STRING,
 LAST_TIME STRING
)PARTITIONED BY(STAT_DATE STRING, REL_TYPE STRING, `TYPE` STRING)
STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

CREATE EXTERNAL TABLE IF NOT EXISTS VEHICLE_FRONT_FACE_INFO(
 INFO_ID STRING,
 DRIVER_FACE_INFO_ID STRING,
 DRIVER_FACE_URL STRING,
 CO_DRIVER_FACE_INFO_ID STRING,
 CO_DRIVER_FACE_URL STRING,
 STORAGE_URL STRING,
 PLATE_NO STRING,
 PLATE_COLOR INT,
 DEVICE_ID STRING,
 TOLLGATE_ID STRING,
 PASS_TIME STRING,
 VIID_OBJECT_ID STRING,
 LONGITUDE STRING,
 LATITUDE STRING
)PARTITIONED BY (
  STAT_DAY STRING,
  `HOUR` STRING)
 STORED AS ORC TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");

 ALTER TABLE EFENCE_DETECT_INFO ADD COLUMNS( INFO_ID STRING);
 ALTER TABLE DM_RELATION_DISTRIBUTE_DETAIL ADD COLUMNS( INFO_ID_A STRING);
 ALTER TABLE DM_RELATION_DISTRIBUTE_DETAIL ADD COLUMNS( INFO_ID_B STRING);

 ALTER TABLE VEHICLE_FRONT_FACE_INFO CHANGE DRIVER_FACE_INFO_ID DRIVER_FACE_VIID_ID string;
 ALTER TABLE VEHICLE_FRONT_FACE_INFO CHANGE CO_DRIVER_FACE_INFO_ID CO_DRIVER_FACE_VIID_ID string;

 ALTER TABLE DM_LCSS_DAY ADD COLUMNS( SEQ_STR_SAME_INFO_A STRING);
 ALTER TABLE DM_LCSS_DAY ADD COLUMNS( SEQ_STR_SAME_INFO_B STRING);